apiVersion: v2
name: omni-sag
description: Auditable SSH/SFTP privileged-access gateway (Omni-SAG)
type: application
version: 0.3.0
appVersion: "1.9.3"
kubeVersion: ">=1.25.0-0"
sources:
  - https://github.com/rupivbluegreen/omni-sag
